@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.almostlib;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
