modLoader = "javafml"
loaderVersion = "[${forge_loader_version},)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${testmod_id}"
version = "${version}"
displayName = "AlmostReliable Testmod"
authors = "${mod_author}"
description = '''
AlmostReliable Testmod
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
