@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.almostlib.network.synchronizer;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
